### PR TITLE
Set up Jest + Enzyme testing environment

### PR DESCRIPTION
**Pull request by echoghi**
Related to #12 

- Added Jest + Enzyme testing env.

- Added simple unit test for `useWindowSize` Hook.

### CODE REVIEW

**Comment by DanielRuf** [comment]
I suggest to add Travis CI for testing every commit and PR.

**Comment by DanielRuf** [comment]
I suggest adding Travis CI for testing every commit and PR.

**Comment by jaredpalmer** [comment]
I would prefer we use Kent's thing react-testing-library over enzyme.

**Comment by echoghi** [comment]
@jaredpalmer I'm down for that, been meaning to try it out.

**Pull request closed without merging**
