### PR TITLE
update example to React v16.8.1

### PR DESCRIPTION
**Pull request by subtleGradient**

### CODE REVIEW

**Comment by jaredpalmer** [comment]
💯💯💯

**Comment by jaredpalmer** [comment]
Wait does 16.8.1 have the suspense stuff we need?

**Comment by subtleGradient** [comment]
🤷‍♂️

**Comment by jaredpalmer** [comment]
lol

**Comment by jaredpalmer** [comment]
Yeah so we are pretty screwed now because react-cache was not published with 16.8.1 like the rest of the react packages. This means that the platform's Suspense stuff will not work.

**Comment by jaredpalmer** [comment]
Yeah it looks like react-cache is incompatible at the moment with 16.8.1

**Comment by gaearon** [comment]
Can you just vendor the parts of react cache that you use? It’s not ever supposed to be dependent upon.

**Comment by jaredpalmer** [comment]
Let me try that out.

**Comment by jaredpalmer** [comment]
Yeah so it looks like react-cache was improperly included as a real dep and not a peer dep. However, to run the suspense focused demo, the suspense components do indeed rely on reach-cache being compatible with the version of react. I can vendor react-cache, but will need to go through and figure out what is actually causing the issue. 

When I try to run the example with 16.8.1 I get the following error from react-cache alpha 1.

```
Uncaught Error: react-cache: read and preload may only be called from within a component's render. They are not supported in event handlers or lifecycle methods.
    at readContext (react-cache.development.js:246)
    at Object.read (react-cache.development.js:316)
    at Video (Video.js:29)
    at renderWithHooks (react-dom.development.js:12749)
    at mountIndeterminateComponent (react-dom.development.js:14679)
    at beginWork (react-dom.development.js:15203)
    at performUnitOfWork (react-dom.development.js:18789)
    at workLoop (react-dom.development.js:18834)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
```

**Comment by jaredpalmer** [comment]
Alright going to try to build react-cache from master

**Comment by gaearon** [comment]
You can find readContext implementation in a bunch of places in our tests. Note it’s not guaranteed to be stable either.

**Comment by jaredpalmer** [comment]
Hrmmmmmmm. This is an afternoon or so of work if someone wants to do it. We could also write our own cache ;-) and just not expose it. It is not very likely a user would want to flush an image cache ever.

**Comment by jaredpalmer** [comment]
@gaearon figured it out. thanks for the help!

**Pull request closed without merging**
